---
layout: post
title: 오늘 배운것 : 스레드
date: 2019-01-22
excerpt: 스레드 예외발생
image: ""
sitemap :
  changefreq : daily
  priority : 1.0
---

<div>
  <p>
    오늘은 웹서버가 웹DB와 앱DB를 바라보기때문에 앱DB가 앱 업데이트같은걸로 꺼지면 스레드가 멈춰버리는걸 해결하기위해 수동으로<br/>
    스레드상태를 체크하여 스레드가 죽어있으면 다시 시작시키는 기능을 구현하였다.<br/>
    테스트를 하기위해 예외를 발생시켜야하는데....사실 try catch는 책에서만봤지 실전은 처음이였다...<br/>
    나는 아래와같이 했다...<br/>
    
  </p>
  <pre>
    <code>
      try {
        while(true&플래그변수) {
          스레드 돌 함수
        }
      } catch(Exception e) {
        플래그 변수 = 0;
      }
    </code>
  </pre>
  <p>
  이런식으로 해주면 while문 안에서 발생한 모든예외는 다 캐치해서 멈춰주면된다 라고 생각했다.<br/>
  테스트할때 우리는 VPN을 사용하여 DB접속을 보안하고있는데 여기서 VPN을 꺼버리면 catch를 타는지 테스트를 해보는도중<br/>
  log4j를 끄지않고 하였다가 1분뒤에 에러 로그가 찍히고 1분뒤에 다시 에러로그가 찍히고 catch를 타는것이였다!<br/>
  에러로그가 두번찍혀서 당연히 얘가 while문을 두번돌았구나 라고 생각하고 계속 왜 첫번째는 catch를 안탄걸까 <br/>
  삽질을 열심히 했다...그리고 욕을 바가지로 먹은다음 log4j를 끄고 보니 결국 정상적으로 작동하는것이였다!<br/>
  그냥 log4j 로그 찍는시간이 걸렸나보다...젠장 괜히 욕만 무진장 먹었다 다음부터는 좀 더 꼼꼼하게 sysout이라도 다찍어보면서<br/>
  다시한번 잘 보고 log4j도 켜졌을때 어떤지 꺼졌을때 어떤지 자세히 보도록 해야겠다...하..ㅠㅠ 다만들고 욕먹어서 슬프다<br/>
  </p>
  <p>
    아 과장님이 팁을 알려줬다! 아래와 같이 while문 통째로 감싸지말고 while문 안에서 try catch를 선언후 플래그 변수를 변경해서 스레드를<br/>
    빠져나오게 하는게 좋다고하였다. 왜냐하면 지금은 어떤 에러가 뜨든 스레드를 죽여야하는것이지만 TCP/IP혹은 예외마다 다른 처리를 해줘야할때<br/>
    저렇게 while을 감싸버리면 답이없다고 하였다! 주의하자
    
  </p>
  <pre>
    <code>
      while(true&플래그변수) {
        try {
          스레드 돌 함수
        } catch(Exception e) {
            플래그 변수 = 0;
        }
      } 
    </code>
  </pre>
  
</div>
